services:
  server:
    image: hisyamsk/url-shortener
    build:
      context: ./
      dockerfile: ./Dockerfile
    init: true
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=foobarbaz
      - DB_PORT=5432
      - APP_PORT=:8000
    networks:
      - backend
    ports:
      - 8000:8000
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  backend:
